name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: write

jobs:
  npm-publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci
      
      - name: Update Version
        run: |
          CLEAN_VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          npm version $CLEAN_VERSION --no-git-tag-version

      - name: Publish to NPM
        # Added logic to handle prerelease tags
        run: |
          if [[ "${{ github.ref_name }}" == *"-"* ]]; then
            npm publish --provenance --access public --tag next
          else
            npm publish --provenance --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  windows-build:
    name: Build Windows Executable
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun install
      - name: Compile Executable
        run: bun build --compile index.js --outfile index.exe
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: index.exe
